name: 'Pull Request Comment'

on:
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]
    
permissions:
  contents: read
  pull-requests: write

jobs:
  write-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: "Don't forget to run the integration tests"
        env:
          GITHUB_TOKEN: ${{secrets.ACTIONS_SECRET}}
