name: 'Pull Request Comment'

on:
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]
    
permissions:
  contents: read
  pull-requests: write

jobs:
  write-pr-comment:
      if: github.event.review.state == 'approved'
      runs-on: ubuntu-latest
      steps:
        - name: OQ test reminder
          uses: thollander/actions-comment-pull-request@v2.3.1
          with:
            message: "Don't forget to run the integration tests"
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        - name: Ping Vankata
          uses: thollander/actions-comment-pull-request@v2.3.1
          with:
            message: "@aleksandarObreshkov"
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
