package model;

import com.fasterxml.jackson.annotation.JsonTypeName;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@EqualsAndHashCode(callSuper = true)
@Entity
@DiscriminatorValue(value = "droid")
@JsonTypeName("droid")
@Data
public class Droid extends Character{

    @NotNull(message = "Please specify the primary function of the droid.")
    private String primaryFunction;

    @Override
    public String getCharacterType() {
        return "droid";
    }

    // TODO Having a no-arg constructor is not necessary - Java adds one if it doesn't exist. I assume these were generated by your IDE.
    // If so, disable that setting, as these are just visual noise.
    public Droid() {
        super();
    }

    public String getPrimaryFunction() {
        return primaryFunction;
    }

    public void setPrimaryFunction(String primaryFunction) {
        this.primaryFunction = primaryFunction;
    }

}
